---
apiVersion: v1
kind: Pod
metada:
  name: resourcelimit
spec:
  containers:
    - name: resourcelimit
      image: nginx:alpine
      resources:
        requests:
          memory: '2Gi'
          cpu: '500m'
        limits:
          memory: '3Gi'
          cpu: '1'
