apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-gcr-deployment
  labels:
    app: hello-app-gcr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app-gcr
  template:
    metadata:
      labels:
        app: hello-app-gcr
    spec:
      containers:
      - name: hello-app-gcr
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 80
