---
apiVersion: v1
kind: Pod
metadata:
  name: execaction-liveness
spec:
  containers:
    - name: execaction-liveness
      image: k8s.gcr.io/busybox

      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30;
        rm -rf /tmp/healthy; sleep 600

      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
