---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
    - name: readiness-probe
      image: nginx:alpine
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 4
        periodSeconds: 2
